# Generated by Django 5.2.6 on 2025-10-31 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="core.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="uniq_user_project"
            ),
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="role",
        ),
    ]
