# Generated by Django 5.2.6 on 2025-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_comment_options_alter_contributor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To do"),
                    ("IN_PROGRESS", "In progress"),
                    ("FINISHED", "Finished"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
